# -*- coding: utf-8 -*-
"""Strings

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B3qGcUUUiqfUH_5JVw32HdbjrwHvM3B6
"""

#Lucas Vandenakker
#CS-175
#Strings

str = input("Please enter a sentance: ")

count = 0;

for i in (str.lower()):

  if(i == "t"):
    count +=1



print(f"The letter T appears {count} times")

#Lucas Vandenakker
#CS-175
#Date

date = "11/23/2024"

list1 = date.split("/")

print(f"Month: {list1[0]} \nDay: {list1[1]}\nYear: {list1[2]}")

#Lucas Vandenakker
#CS-175
#user name and login


firstName = input("Please enter your first name: ")
lastName = input("Please enter your last name: ")
idNum = input("Please enter your student ID number: ")

userName = firstName[0:3] + lastName[0:3] + idNum[len(idNum)-3:len(idNum)]

print(f"Your user name is {userName.lower()}")

#Lucas Vandenakker
#CS-175
#passowrd

correct_length = False
has_uppercase = False
has_lowercase = False
has_digit = False

password = input("Please enter a valid password: ")

if(len(password) >= 7 ):
  correct_length = True

  for i in password:
    if(i.isupper()):
      has_uppercase = True


  if(has_uppercase):
    for j in password:
      if(not(j.isupper())):
        has_lowercase = True

    if(has_lowercase):

      for x in password:
        if(i.isdigit()):
          has_digit = True

      if(has_digit):

         print("True")

      else:
        print("False")

    else:
      print("False")
  else:
    print("False")
else:
  print("False")